name: Build_Kernel

on:
  release:
    types: [published]
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04

    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main

      - name: Configuration Environment
        run: |
          sudo apt update && sudo apt -y dist-upgrade
          sudo apt install -y gcc g++ python make texinfo texlive bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip language-pack-zh-hans
          git config --global user.name "demokernel"
          git config --global user.email "demokernel@hotmail.com"

      - name: Clone device kernel
        run: |
          cd $GITHUB_WORKSPACE
          git clone --depth=1 https://github.com/lineageos/android_kernel_xiaomi_sm8250.git -b lineage-19.1

      - name: Clone compiler && Building kernel
        run: |
          cd $GITHUB_WORKSPACE/android_kernel_xiaomi_sm8250
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git -b lineage-19.1
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=${PWD}/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/aarch64-none-linux-gnu-
          mkdir out
          make clean
          make mrproper
          make -j$(nproc --all) O=out vendor/lmi_defconfig
          make -j$(nproc --all) O=out
